### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tinyheero** [SchubertLab/JessEV#1]
Hi there,

What's the license on this tool? I don't see a LICENSE file in the repository and there isn't any mention of a license in the paper (https://academic.oup.com/bioinformatics/article/36/Supplement_2/i643/6055919).

**Comment by e-dorigatti** [comment]
Hi @tinyheero, thank you for your interest! We are planning to adopt a dual licensing scheme - a permissive one for academic usage and a more restrictive one for commercial usage. Our innovation department is (still) looking into it, but if you send us an email with more details on your use-case we might be able to speed this process up.

**Comment by tinyheero** [comment]
Thanks @e-dorigatti! I'll reach out to you in an email.
